/** English / Hebrew names for FluidSIM parts. Keys: the German library description, or the class name. */
type N = [string, string];
const BY_DESC: Record<string, N> = {
  "2/2-Wege-Stößelventil": ["2/2-way plunger valve", "שסתום 2/2 עם בוכנה"],
  "2/n-Wegeventil": ["2/n-way valve (configurable)", "שסתום 2/n (ניתן להגדרה)"],
  "3-Wege Stromregelventil": ["3-way flow control valve", "שסתום ויסות ספיקה 3 דרכים"],
  "3/2-Wege-Handhebelventil": ["3/2-way hand lever valve", "שסתום 3/2 ידית יד"],
  "3/2-Wege-Kipprollenventil": ["3/2-way idle-return roller valve", "שסתום 3/2 גלגלת חד-כיוונית"],
  "3/2-Wege-Magnetventil": ["3/2-way solenoid valve", "שסתום 3/2 סולנואיד"],
  "3/2-Wege-Pneumatikventil": ["3/2-way pneumatic valve", "שסתום 3/2 פיקוד פנאומטי"],
  "3/2-Wege-Rollenhebelventil": ["3/2-way roller lever valve", "שסתום 3/2 גלגלת"],
  "3/2-Wegeventil mit Drucktaster": ["3/2-way valve with push button", "שסתום 3/2 עם לחצן"],
  "3/2-Wegeventil mit Wahlschalter": ["3/2-way valve with selector switch", "שסתום 3/2 עם בורר"],
  "3/n-Wegeventil": ["3/n-way valve (configurable)", "שסתום 3/n (ניתן להגדרה)"],
  "4/2-Wege-Handhebelventil": ["4/2-way hand lever valve", "שסתום 4/2 ידית יד"],
  "4/2-Wege-Magnetventil": ["4/2-way solenoid valve", "שסתום 4/2 סולנואיד"],
  "4/3-Wege Regelventil": ["4/3-way servo valve", "שסתום סרוו 4/3"],
  "4/3-Wege-Handhebelventil mit Sperrstellung": ["4/3-way hand lever valve, closed centre", "שסתום 4/3 ידית יד, מרכז סגור"],
  "4/3-Wege-Handhebelventil mit Stuhlstellung": ["4/3-way hand lever valve, tandem centre", "שסתום 4/3 ידית יד, מרכז טנדם"],
  "4/3-Wege-Handhebelventil, Umlaufstellung": ["4/3-way hand lever valve, open centre", "שסתום 4/3 ידית יד, מרכז פתוח"],
  "4/3-Wege-Magnetventil mit Sperrstellung": ["4/3-way solenoid valve, closed centre", "שסתום 4/3 סולנואיד, מרכז סגור"],
  "4/3-Wege-Magnetventil mit Stuhlstellung": ["4/3-way solenoid valve, tandem centre", "שסתום 4/3 סולנואיד, מרכז טנדם"],
  "4/3-Wege-Magnetventil mit Umlaufstellung": ["4/3-way solenoid valve, open centre", "שסתום 4/3 סולנואיד, מרכז פתוח"],
  "4/3-Wege-Proportionalventil": ["4/3-way proportional valve", "שסתום פרופורציונלי 4/3"],
  "4/n-Wegeventil": ["4/n-way valve (configurable)", "שסתום 4/n (ניתן להגדרה)"],
  "5/2-Wege-Magnet-Impulsventil": ["5/2-way double solenoid valve", "שסתום 5/2 סולנואיד כפול (זיכרון)"],
  "5/2-Wege-Magnetventil": ["5/2-way solenoid valve", "שסתום 5/2 סולנואיד"],
  "5/2-Wege-Pneumatik-Impulsventil": ["5/2-way pneumatic memory valve", "שסתום 5/2 פנאומטי כפול (זיכרון)"],
  "5/2-Wege-Pneumatikventil": ["5/2-way pneumatic valve", "שסתום 5/2 פיקוד פנאומטי"],
  "5/2-Wegeventil mit Wahlschalter": ["5/2-way valve with selector switch", "שסתום 5/2 עם בורר"],
  "5/3-Wege Proportionalventil": ["5/3-way proportional valve", "שסתום פרופורציונלי 5/3"],
  "5/3-Wege-Magnetventil": ["5/3-way solenoid valve", "שסתום 5/3 סולנואיד"],
  "5/3-Wege-Pneumatikventil": ["5/3-way pneumatic valve", "שסתום 5/3 פיקוד פנאומטי"],
  "5/n-Wegeventil": ["5/n-way valve (configurable)", "שסתום 5/n (ניתן להגדרה)"],
  "6/n-Wegeventil": ["6/n-way valve (configurable)", "שסתום 6/n (ניתן להגדרה)"],
  "8/n-Wegeventil": ["8/n-way valve (configurable)", "שסתום 8/n (ניתן להגדרה)"],
  "Analog-Drucksensor": ["Analog pressure sensor", "חיישן לחץ אנלוגי"],
  "Analog-Durchflussmesser": ["Analog flow sensor", "חיישן ספיקה אנלוגי"],
  "Blende": ["Orifice", "מצר קבוע"],
  "Blende, einstellbar": ["Orifice, adjustable", "מצר מתכוונן"],
  "Differenzdruckmessgerät": ["Differential pressure gauge", "מד הפרש לחצים"],
  "Doppeltwirkender Mehrstellungszylinder": ["Double-acting multi-position cylinder", "בוכנה דו-כיוונית רב-מצבית"],
  "Drosselventil": ["Throttle valve", "שסתום חנק"],
  "Druckanzeige": ["Pressure indicator", "מחוון לחץ"],
  "Druckbegrenzungsventil, vorgesteuert": ["Pressure relief valve, pilot operated", "שסתום ביטחון, מפוקד"],
  "Druckluftfilter": ["Air filter", "מסנן אוויר"],
  "Druckluftfilter, manueller Kondensatablass": ["Air filter, manual drain", "מסנן אוויר, ניקוז ידני"],
  "Druckluftquelle": ["Compressed air supply", "מקור אוויר דחוס"],
  "Druckminderventil": ["Pressure reducing valve", "שסתום מוריד לחץ"],
  "Druckminderventil, einstellbar": ["Pressure reducing valve, adjustable", "שסתום מוריד לחץ, מתכוונן"],
  "Druckregelventil": ["Pressure regulator", "וסת לחץ"],
  "Druckregelventil, einstellbar": ["Pressure regulator, adjustable", "וסת לחץ מתכוונן"],
  "Druckspeicher": ["Air reservoir", "מיכל אוויר"],
  "Druckwaage (Schließer)": ["Pressure compensator (normally closed)", "מפצה לחץ (סגור במנוחה)"],
  "Druckwaage (Schließer), einstellbar": ["Pressure compensator (normally closed), adjustable", "מפצה לחץ (סגור במנוחה), מתכוונן"],
  "Druckwaage (Öffner)": ["Pressure compensator (normally open)", "מפצה לחץ (פתוח במנוחה)"],
  "Druckwaage (Öffner), einstellbar": ["Pressure compensator (normally open), adjustable", "מפצה לחץ (פתוח במנוחה), מתכוונן"],
  "Durchflussmesser": ["Flow meter", "מד ספיקה"],
  "Düse": ["Nozzle", "נחיר"],
  "ENTITIES": ["Quick stepper module", "מודול צעד מהיר"],
  "Einbauventil (Schließer)": ["Cartridge valve (normally closed)", "שסתום מחסנית (סגור במנוחה)"],
  "Einbauventil (Öffner)": ["Cartridge valve (normally open)", "שסתום מחסנית (פתוח במנוחה)"],
  "Filter": ["Filter", "מסנן"],
  "Heizung": ["Heater", "מחמם"],
  "Konstantpumpe": ["Fixed displacement pump", "משאבה בספיקה קבועה"],
  "Kühler": ["Cooler", "מצנן"],
  "Linearantrieb, pneumatisch, mit formschlüssiger Verbindung": ["Pneumatic linear drive, positive coupling", "מנוע ליניארי פנאומטי, צימוד מכני"],
  "Motor oscilante, lineal ": ["Semi-rotary actuator", "מפעיל סיבובי חלקי"],
  "Niederdruck-Verstärker-Baustein": ["Low-pressure amplifier", "מגבר לחץ נמוך"],
  "Pneumatischer Näherungsschalter, magnetisch betätigt": ["Pneumatic proximity switch, magnetic", "חיישן קרבה פנאומטי, מגנטי"],
  "Pneumatischer Timer, in Ruhestellung gesperrt": ["Pneumatic timer, normally closed", "טיימר פנאומטי, סגור במנוחה"],
  "Pneumatischer Timer, in Ruhestellung geöffnet": ["Pneumatic timer, normally open", "טיימר פנאומטי, פתוח במנוחה"],
  "Proportional-Drosselventil": ["Proportional throttle valve", "שסתום חנק פרופורציונלי"],
  "Proportional-Druckbegrenzungsventil": ["Proportional pressure relief valve", "שסתום ביטחון פרופורציונלי"],
  "Proportional-Druckbegrenzungsventil, vorgesteuert": ["Proportional pressure relief valve, pilot operated", "שסתום ביטחון פרופורציונלי, מפוקד"],
  "Proportional-Druckregelventil, vorgesteuert": ["Proportional pressure reducing valve, pilot operated", "שסתום מוריד לחץ פרופורציונלי, מפוקד"],
  "Proportional-Verstellpumpe": ["Proportional variable pump", "משאבה משתנה פרופורציונלית"],
  "Rückschlagventil": ["Check valve", "שסתום אל-חוזר"],
  "Rückschlagventil mit Feder": ["Check valve, spring loaded", "שסתום אל-חוזר עם קפיץ"],
  "Rückschlagventil mit Feder, entsperrbar": ["Pilot-to-open check valve, spring loaded", "שסתום אל-חוזר מפוקד לפתיחה, עם קפיץ"],
  "Rückschlagventil mit Feder, sperrbar": ["Pilot-to-close check valve, spring loaded", "שסתום אל-חוזר מפוקד לסגירה, עם קפיץ"],
  "Rückschlagventil, entsperrbar": ["Pilot-to-open check valve", "שסתום אל-חוזר מפוקד לפתיחה"],
  "Rückschlagventil, sperrbar": ["Pilot-to-close check valve", "שסתום אל-חוזר מפוקד לסגירה"],
  "Speicher": ["Accumulator", "מצבר הידראולי"],
  "Staudruckventil": ["Back-pressure valve", "שסתום לחץ חוזר"],
  "Verdichter, einstellbar": ["Compressor, adjustable", "מדחס מתכוונן"],
  "Verstellpumpe": ["Variable displacement pump", "משאבה בספיקה משתנה"],
  "Válvula distribuidora de caudal ": ["Flow divider valve", "שסתום מחלק ספיקה"],
  "Válvula reguladora de presión ": ["Pressure regulating valve", "שסתום ויסות לחץ"],
  "Wasserabscheider mit automatischer Entleerung": ["Water separator, automatic drain", "מפריד מים, ניקוז אוטומטי"],
  "Wasserabscheider, handbetätigt": ["Water separator, manual drain", "מפריד מים, ניקוז ידני"],
  "Zweihandsteuerblock": ["Two-hand control block", "יחידת הפעלה בשתי ידיים"],
  "Zylinder, doppeltwirkend": ["Double-acting cylinder", "בוכנה דו-כיוונית"],
  "Zylinder, doppeltwirkend, mit durchgehender Kolbenstange": ["Double-acting cylinder, through rod", "בוכנה דו-כיוונית, מוט עובר"],
  "Zylinder, doppeltwirkend, mit zwei Kolbenstangen und einem Joch": ["Double-acting cylinder, twin rods with yoke", "בוכנה דו-כיוונית, שני מוטות ועול"],
  "Zylinder, doppeltwirkend, mit zwei durchgehenden Kolbenstangen und doppeltem Joch": ["Double-acting cylinder, twin through rods, double yoke", "בוכנה דו-כיוונית, שני מוטות עוברים ועול כפול"],
  "Zylinder, einfachwirkend, Rückstellfeder im Kolbenraum": ["Single-acting cylinder, spring return", "בוכנה חד-כיוונית, החזרת קפיץ"],
  "Zylinder, ohne Kolbenstange": ["Rodless cylinder", "בוכנה ללא מוט"],
  "Öler": ["Lubricator", "משמן"],
};
const BY_CLASS: Record<string, N> = {
  PPE1: ["Compressed air supply", "מקור אוויר דחוס"],
  PPE2: ["Pressure regulator", "וסת לחץ"],
  PRV: ["Service unit (filter, regulator)", "יחידת טיפול באוויר"],
  man1: ["Pressure gauge", "מד לחץ"],
  tank1: ["Tank", "מיכל שמן"],
  Ag1: ["Hydraulic power unit", "יחידת כוח הידראולית"],
  Ag2: ["Hydraulic power unit (detailed)", "יחידת כוח הידראולית (מפורטת)"],
  dbv: ["Pressure relief valve", "שסתום ביטחון"],
  drv: ["Pressure reducing valve, 3-way", "שסתום מוריד לחץ 3 דרכים"],
  srv: ["Flow control valve", "שסתום ויסות ספיקה"],
  drossel: ["Throttle valve", "שסתום חנק"],
  absperr: ["Shut-off valve", "ברז סגירה"],
  drorueck: ["One-way flow control valve", "שסתום חנק חד-כיווני"],
  DRSV2: ["One-way flow control valve, horizontal", "שסתום חנק חד-כיווני, אופקי"],
  V16: ["Pressure sequence valve", "שסתום רצף לחץ"],
  rsvfed: ["Check valve, spring loaded", "שסתום אל-חוזר עם קפיץ"],
  motor: ["Hydraulic motor", "מנוע הידראולי"],
  duflu: ["Hydraulic motor with flow display", "מנוע הידראולי עם תצוגת ספיקה"],
  SemiRotaryMotorH: ["Semi-rotary actuator", "מפעיל סיבובי חלקי"],
};
export function fluidName(cls: string, desc: string, lang: string): string {
  const n = BY_CLASS[cls] || BY_DESC[desc];
  if (n) return lang === "he" ? n[1] : n[0];
  return desc || cls;
}
