/** Strings used only by the pneumatic and hydraulic programs (shared ones are in shared/i18n.ts). */
export const FS = {
  en: {
    tube: "Tube", newName: "New circuit",
    groups: { actuator: "Actuators", supply: "Supply & air/oil treatment", valve: "Valves", vgroup: "Valve groups", sensor: "Measuring & sensors", other: "Other (from example circuits)" } as Record<string, string>,
    placeHint: "Click on the sheet to place it. R rotates, Esc cancels.",
    tubeHint: "Click a port, add bends by clicking the sheet, then click another port. Esc cancels.",
    selHint: "Drag parts to move them. Drag from a port to draw a tube. R rotates, Del deletes, Ctrl+Z undoes.",
    part: "Part", ports: "Ports", props: "Parameters", cls: "FluidSIM class", config: "Valve configuration",
    tubeSel: "Tube", from: "From", to: "To", bends: "Bends",
    openCt: "Open FluidSIM file (.ct)", saveJson: "Save project (.json)", openJson: "Open project (.json)",
    ctNote: "Opens circuits saved by FluidSIM 4. Saving back to .ct is not ready yet; for now save the project as .json.",
    imported: (n: number, t: number) => `Imported ${n} parts and ${t} tubes.`,
    skipped: "Not shown (text, pictures, diagrams)", wrongProgram: (p: string) => `This file was made in FluidSIM ${p}; it opens here, but belongs to the ${p === "H" ? "hydraulics" : "pneumatics"} program.`,
    parts: "parts", tubes: "tubes", 
    exP1: "Cylinder with 5/2 valve", exP2: "Cylinder, two 3/2 valves", exH1: "Electro-hydraulic cylinder",
    openPort: "free",
    edit: "Edit", sim: "▶ Simulate", simTitle: "Simulation",
    simHint: "Click a valve's actuator side to operate it: push buttons and rollers while held, solenoids switch on/off. Pilot-operated valves follow their pilot pressure. Shift+click latches a push button (to operate two at once). Click a shut-off valve to close it.",
    legP: "Under pressure", legNoP: "No pressure / exhaust", cylinders: "Cylinders",
  },
  he: {
    tube: "צינור", newName: "מעגל חדש",
    groups: { actuator: "מפעילים", supply: "אספקה וטיפול באוויר/שמן", valve: "שסתומים", vgroup: "קבוצות שסתומים", sensor: "מדידה וחיישנים", other: "אחר (ממעגלי הדוגמה)" } as Record<string, string>,
    placeHint: "לחץ על הדף כדי למקם. R מסובב, Esc מבטל.",
    tubeHint: "לחץ על יציאה, הוסף כיפופים בלחיצה על הדף, ואז לחץ על יציאה אחרת. Esc מבטל.",
    selHint: "גרור רכיבים כדי להזיז. גרור מיציאה כדי למתוח צינור. R מסובב, Del מוחק, Ctrl+Z מבטל.",
    part: "רכיב", ports: "יציאות", props: "פרמטרים", cls: "מחלקה ב-FluidSIM", config: "תצורת שסתום",
    tubeSel: "צינור", from: "מ", to: "אל", bends: "כיפופים",
    openCt: "פתח קובץ FluidSIM ‏(.ct)", saveJson: "שמור פרויקט (.json)", openJson: "פתח פרויקט (.json)",
    ctNote: "פותח מעגלים שנשמרו ב-FluidSIM 4. שמירה חזרה ל-.ct עוד לא מוכנה; בינתיים אפשר לשמור את הפרויקט כ-.json.",
    imported: (n: number, t: number) => `יובאו ${n} רכיבים ו-${t} צינורות.`,
    skipped: "לא מוצג (טקסט, תמונות, דיאגרמות)", wrongProgram: (p: string) => `הקובץ נוצר ב-FluidSIM ${p}; הוא נפתח כאן, אבל שייך לתוכנת ה${p === "H" ? "הידראוליקה" : "פנאומטיקה"}.`,
    parts: "רכיבים", tubes: "צינורות", 
    exP1: "בוכנה עם שסתום 5/2", exP2: "בוכנה ושני שסתומי 3/2", exH1: "בוכנה אלקטרו-הידראולית",
    openPort: "פנויה",
    edit: "עריכה", sim: "▶ סימולציה", simTitle: "סימולציה",
    simHint: "לחץ על צד המפעיל של שסתום כדי להפעיל אותו: לחצנים וגלגלות כל עוד מחזיקים, סולנואידים נדלקים ונכבים. שסתומים בפיקוד פנאומטי מגיבים ללחץ הפיקוד. Shift+לחיצה נועלת לחצן במצב לחוץ (כדי להפעיל שניים יחד). לחיצה על ברז סגירה סוגרת אותו.",
    legP: "תחת לחץ", legNoP: "בלי לחץ / פליטה", cylinders: "בוכנות",
  },
};
export type FStrings = typeof FS.en;
